name: MacOS 64-Bit Build
on: push
jobs:
  gradle:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: FuuGBemuExecutable