name: Mac OSX 64-Bit Build

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: make debug