name: Tagged Release

on:
  push:
    tags:
    - 'v*'

jobs:
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
  build-windows:
    needs: createRelease
    name: Upload Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make debug
      - name: Compress
        run: tar -cvzf FuuGBemu.tar.gz ${{github.workspace}}\build\bin
      - name: Upload Package
        id: upload-FuuGBemu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createRelease.outputs.upload_url }}
          asset_path: ${{github.workspace}}\FuuGBemu.tar.gz
          asset_name: win_x86-64_FuuGBemu
          asset_content_type: application/zip
  build-macos:
    needs: createRelease
    name: Upload OSX
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make debug
      - name: Compress
        run: tar -cvzf FuuGBemu.tar.gz ${{github.workspace}}/build/bin
      - name: Upload Package
        id: upload-FuuGBemu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createRelease.outputs.upload_url }}
          asset_path: ${{github.workspace}}/FuuGBemu.tar.gz
          asset_name: macos_x86-64_FuuGBemu
          asset_content_type: application/zip