name: Windows 64-Bit Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: make
      run: make debug
    - name: upload binary
      uses: actions/upload-artifact@v2
      with:
        name: build_${env.GITHUB_REF}
        path: ${{github.workspace}}\build\bin\